development: &DEVELOPMENT
  adapter: mysql
  database: nodemap_development
  username: root
  password: password
  host: localhost
  
test:
  <<: *DEVELOPMENT
  database: nodemap_test

production:
  <<: *DEVELOPMENT
  database: nodemap_production
